server:
  port: 8099
  servlet:
    context-path: /
spring:
  application:
    name: farm-manage-system
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/farm?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: xhua


logging:
    level:
        com.farm.mapper: debug

